version: '3'
services:
  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - backend
    networks:
      yolo-network:
        ipv4_address: 172.20.0.10
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      MONGODB_URI: 'mongodb://yolo:yolo123@172.20.0.1:27017/'
    depends_on:
      - database
    networks:
      yolo-network:
        ipv4_address: 172.20.0.20
  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: yolo
      MONGO_INITDB_ROOT_PASSWORD: yolo123
    ports:
      - 27017:27017
    networks:
      yolo-network:
        ipv4_address: 172.20.0.100
networks:
  yolo-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16